In [1]:
import pandas as pd

In [2]:
bldgs = pd.read_csv('bbb-results.csv')
bldgs

,name,categories,address,phone,rating,url
0,Indigo Riverview,Apartments,"99 N Main St,\nMemphis, TN 38103",NaN,BBB Rating: D+,https://www.bbb.org/us/tn/memphis/profile/apar...
1,99 Front Street,"Property Management, Apartments, Real Estate C...","99 S Front St,\nMemphis, TN 38103",(901) 767-6500,BBB Rating: A+,https://www.bbb.org/us/tn/memphis/profile/prop...
2,The Renaissance Apartments,Apartments,"99 N Main St,\nMemphis, TN 38103",(901) 527-8057,BBB Rating: B-,https://www.bbb.org/us/tn/memphis/profile/apar...
3,2nd Street Flats,Apartments,"275 South Second Street,\nMemphis, TN 38103",(901) 774-8000,BBB Rating: A+,https://www.bbb.org/us/tn/memphis/profile/apar...
4,"Fogelman Properties, Inc.","Property Management, Apartments, Real Estate C...","495 Tennessee Street,\nMemphis, TN 38103",(833) 706-9514,BBB Rating: A+,https://www.bbb.org/us/tn/memphis/profile/prop...
...,...,...,...,...,...,...
271,Tree Haven Glenn Apartments,Apartments,"6075 Poplar Ave STE 630,\nMemphis, TN 38119-4702",(256) 881-6201,BBB Rating: A+,https://www.bbb.org/us/al/huntsville/profile/a...
272,Courts at Waterford Place,Apartments,"5545 Murray Ave 3rd FL,\nMemphis, TN 38119",(901) 435-9300,BBB Rating: A-,https://www.bbb.org/us/tn/chattanooga/profile/...
273,Richard & Milton Grant LLC,Apartments,"7542 Legacy Drive,\nMemphis, TN 38119",(901) 755-8480,BBB Rating: A+,https://www.bbb.org/us/tn/memphis/profile/apar...
274,Ridgeway Holdings LLC,Apartments,"6033 Bangalore Ct,\nMemphis, TN 38119-7200",(901) 767-1830,BBB Rating: F,https://www.bbb.org/us/tn/memphis/profile/apar...
275,"Apartment Management Group, LLC",Apartments,"5264 Poplar Ave,\nMemphis, TN 38119",(901) 761-3333,BBB Rating: A+,https://www.bbb.org/us/tn/memphis/profile/apar...

In [98]:
comps = pd.read_csv('bbb-complaints.csv')
comps

,complaint_type,complaint_id,status,date,description,text,url
0,Problems with Product/Service,1504025924,Unanswered,03/21/2023,Initial Complaint,I moved out of this building (now Indigo River...,https://www.bbb.org/us/tn/memphis/profile/apar...
1,Problems with Product/Service,1590525145,Answered,04/04/2023,Initial Complaint,This business removes autopay from resident po...,https://www.bbb.org/us/tn/memphis/profile/prop...
2,Problems with Product/Service,1590525145,Answered,04/05/2023,Business response,The resident payment portal is set up and cont...,https://www.bbb.org/us/tn/memphis/profile/prop...
3,Problems with Product/Service,1590525145,Answered,04/05/2023,Customer response,\nComplaint: 19895253\n\nI am rejecting this ...,https://www.bbb.org/us/tn/memphis/profile/prop...
4,Problems with Product/Service,1590525145,Answered,04/17/2023,Business response,The resident keeps referencing the amount of h...,https://www.bbb.org/us/tn/memphis/profile/prop...
...,...,...,...,...,...,...,...
1184,Advertising/Sales Issues,1424905505,Resolved,11/16/2020,Initial Complaint,"After vacating the apartment, the final balanc...",https://www.bbb.org/us/tn/chattanooga/profile/...
1185,Advertising/Sales Issues,1424905505,Resolved,12/02/2020,Business response,"Business Response /* (1000, 5, 2020/11/16) */ ...",https://www.bbb.org/us/tn/chattanooga/profile/...
1186,Problems with Product/Service,1304387016,Unanswered,08/03/2022,Initial Complaint,I recently applied for the town home apartment...,https://www.bbb.org/us/tn/memphis/profile/apar...
1187,Advertising/Sales Issues,1304387015,Unanswered,04/09/2021,Initial Complaint,"These apartments refuse to fix anything, I hav...",https://www.bbb.org/us/tn/memphis/profile/apar...
1188,Billing/Collection Issues,1304387014,Unanswered,10/05/2020,Initial Complaint,Still haven't properly been help ...carpet sti...,https://www.bbb.org/us/tn/memphis/profile/apar...

In [4]:
x = pd.merge(bldgs, comps,on='url',how='right')

In [5]:
x.groupby('name').count()

,categories,address,phone,rating,url,complaint_type,complaint_id,status,date,description,text
name,,,,,,,,,,,
99 Front Street,78,78,78,78,78,78,78,78,78,78,78
"ALCO Management, Inc.",368,368,368,368,368,368,368,368,368,368,368
Abington Apartments,8,8,8,8,8,8,8,8,8,8,8
Annie's Townhomes,2,2,2,2,2,2,2,2,2,2,2
Arbors of Hickory Ridge,13,13,13,13,13,13,13,13,13,13,13
...,...,...,...,...,...,...,...,...,...,...,...
Vantage at Germantown,2,2,2,2,2,2,2,2,2,2,2
Westside Manor Apartments,2,2,0,2,2,2,2,2,2,2,2
Whitney Manor Apartments,1,1,1,1,1,1,1,1,1,1,1
Winchester Grove Apartments,6,6,6,6,6,6,6,6,6,6,6
Yugo Memphis Southern,10,10,10,10,10,10,10,10,10,10,10

In [6]:
bldgs.groupby('name').count()

                             categories  address  phone  rating  url
name
2nd Street Flats                      2        2      2       2    2
99 Front Street                       1        1      1       1    1
ALCO Management, Inc.                16       16     16      16   16
Abington Apartments                   1        1      1       1    1
Annie's Townhomes                     1        1      1       1    1
...                                 ...      ...    ...     ...  ...
Winchester Grove Apartments           1        1      1       1    1
Windsor Place Apartments              1        1      1       1    1
Wofford Realty,Co.                    2        2      2       2    2
Woodlake Apartments                   1        1      1       1    1
Yugo Memphis Southern                 1        1      1       1    1

[174 rows x 5 columns]

In [7]:
bldgs.groupby('url').count()

,name,categories,address,phone,rating
url,,,,,
https://www.bbb.org/us/al/huntsville/profile/apartments/tree-haven-glenn-apartments-0513-900089241,1,1,1,1,1
https://www.bbb.org/us/nc/greensboro/profile/property-management/bell-partners-inc-0503-4006931,1,1,1,1,1
https://www.bbb.org/us/or/corvallis/profile/apartments/corvallis-or-student-housing-owner-llc-1296-1000021472,1,1,1,1,1
https://www.bbb.org/us/pa/philadelphia/profile/apartments/madison-apartment-group-0241-180015313,1,1,1,1,1
https://www.bbb.org/us/tn/chattanooga/profile/apartments/courts-at-waterford-place-0483-31000023,1,1,1,1,1
...,...,...,...,...,...
https://www.bbb.org/us/tn/memphis/profile/property-management/makowsky-ringel-greenberg-llc-0543-3304,1,1,1,1,1
https://www.bbb.org/us/tn/memphis/profile/property-management/pauline-place-apartments-0543-44002189,1,1,1,1,1
https://www.bbb.org/us/tn/memphis/profile/property-management/the-sunshine-corporation-0543-6721,4,4,4,4,4
https://www.bbb.org/us/tn/memphis/profile/senior-living/glendale-apartments-0543-44151431,1,1,1,1,1
https://www.bbb.org/us/tn/mempis/profile/apartments/tanglewood-apartments-0543-44156563,1,1,1,1,1

In [37]:
comps.groupby('description').count()

                   complaint_type  complaint_id  status  date  text  url
description
Business response             469           469     469   469   469  469
Customer response             191           191     191   191   191  191
Initial Complaint             529           529     529   529   529  529

In [40]:
comps.groupby('complaint_id').count()

              complaint_type  status  date  description  text  url
complaint_id
1299364647                 1       1     1            1     1    1
1299366377                 1       1     1            1     1    1
1299367493                 1       1     1            1     1    1
1299367494                 1       1     1            1     1    1
1299367548                 2       2     2            2     2    2
...                      ...     ...   ...          ...   ...  ...
1593791406                 2       2     2            2     2    2
1593791407                 3       3     3            3     3    3
1593791408                 2       2     2            2     2    2
1593791409                 4       4     4            4     4    4
1593791410                 2       2     2            2     2    2

[529 rows x 6 columns]

In [8]:
comps

,complaint_type,complaint_id,status,date,description,text,url
0,Problems with Product/Service,1504025924,Unanswered,03/21/2023,Initial Complaint,I moved out of this building (now Indigo River...,https://www.bbb.org/us/tn/memphis/profile/apar...
1,Problems with Product/Service,1590525145,Answered,04/04/2023,Initial Complaint,This business removes autopay from resident po...,https://www.bbb.org/us/tn/memphis/profile/prop...
2,Problems with Product/Service,1590525145,Answered,04/05/2023,Business response,The resident payment portal is set up and cont...,https://www.bbb.org/us/tn/memphis/profile/prop...
3,Problems with Product/Service,1590525145,Answered,04/05/2023,Customer response,\nComplaint: 19895253\n\nI am rejecting this ...,https://www.bbb.org/us/tn/memphis/profile/prop...
4,Problems with Product/Service,1590525145,Answered,04/17/2023,Business response,The resident keeps referencing the amount of h...,https://www.bbb.org/us/tn/memphis/profile/prop...
...,...,...,...,...,...,...,...
1184,Advertising/Sales Issues,1424905505,Resolved,11/16/2020,Initial Complaint,"After vacating the apartment, the final balanc...",https://www.bbb.org/us/tn/chattanooga/profile/...
1185,Advertising/Sales Issues,1424905505,Resolved,12/02/2020,Business response,"Business Response /* (1000, 5, 2020/11/16) */ ...",https://www.bbb.org/us/tn/chattanooga/profile/...
1186,Problems with Product/Service,1304387016,Unanswered,08/03/2022,Initial Complaint,I recently applied for the town home apartment...,https://www.bbb.org/us/tn/memphis/profile/apar...
1187,Advertising/Sales Issues,1304387015,Unanswered,04/09/2021,Initial Complaint,"These apartments refuse to fix anything, I hav...",https://www.bbb.org/us/tn/memphis/profile/apar...
1188,Billing/Collection Issues,1304387014,Unanswered,10/05/2020,Initial Complaint,Still haven't properly been help ...carpet sti...,https://www.bbb.org/us/tn/memphis/profile/apar...

In [62]:
br = 'Business Response'
cr = 'Consumer Response'

In [141]:
def sep_responses(row):
    resps = []
    a = row['text']
    while br in a or cr in a:
        if br in a and cr in a:
            if a.index(br) < a.index(cr):
                ind = a.index(br) + len(br)
                resps.append(br)
                a = a[ind:].strip(' /*')
            else:
                ind = a.index(cr) + len(cr)
                resps.append(cr)
                a = a[ind:].strip('/*')
        elif cr in a:
            ind = a.index(cr) + len(cr)
            resps.append(cr)
            a = a[ind:].strip('/*')
        elif br in a:
            ind = a.index(br) + len(br)
            resps.append(br)
            a = a[ind:].strip(' /*')
    if len(resps) == 0:
        resps.append(row['description'])
    row.loc['description'] = resps
    texts = re.split('Business Response|Consumer Response', row.loc['text'])
    row.loc['text'] = [i for i in texts if i]
    return row

In [175]:
exp = comps.apply(sep_responses,axis=1).explode(column=['description','text'])
exp

,complaint_type,complaint_id,status,date,description,text,url
0,Problems with Product/Service,1504025924,Unanswered,03/21/2023,Initial Complaint,I moved out of this building (now Indigo River...,https://www.bbb.org/us/tn/memphis/profile/apar...
1,Problems with Product/Service,1590525145,Answered,04/04/2023,Initial Complaint,This business removes autopay from resident po...,https://www.bbb.org/us/tn/memphis/profile/prop...
2,Problems with Product/Service,1590525145,Answered,04/05/2023,Business response,The resident payment portal is set up and cont...,https://www.bbb.org/us/tn/memphis/profile/prop...
3,Problems with Product/Service,1590525145,Answered,04/05/2023,Customer response,\nComplaint: 19895253\n\nI am rejecting this ...,https://www.bbb.org/us/tn/memphis/profile/prop...
4,Problems with Product/Service,1590525145,Answered,04/17/2023,Business response,The resident keeps referencing the amount of h...,https://www.bbb.org/us/tn/memphis/profile/prop...
...,...,...,...,...,...,...,...
1185,Advertising/Sales Issues,1424905505,Resolved,12/02/2020,Business Response,"/* (4000, 20, 2020/12/01) */ The collection a...",https://www.bbb.org/us/tn/chattanooga/profile/...
1185,Advertising/Sales Issues,1424905505,Resolved,12/02/2020,Consumer Response,"/* (2000, 22, 2020/12/01) */ (The consumer in...",https://www.bbb.org/us/tn/chattanooga/profile/...
1186,Problems with Product/Service,1304387016,Unanswered,08/03/2022,Initial Complaint,I recently applied for the town home apartment...,https://www.bbb.org/us/tn/memphis/profile/apar...
1187,Advertising/Sales Issues,1304387015,Unanswered,04/09/2021,Initial Complaint,"These apartments refuse to fix anything, I hav...",https://www.bbb.org/us/tn/memphis/profile/apar...
1188,Billing/Collection Issues,1304387014,Unanswered,10/05/2020,Initial Complaint,Still haven't properly been help ...carpet sti...,https://www.bbb.org/us/tn/memphis/profile/apar...

In [192]:
def sep_date(row):
    text = row['text']
    date = row['date']
    if ') */' in text:
        ind = text.index('*/') + 2
        date = text[:ind].strip('/**/ ()').split(', ')[2]
        text = text[ind:]
    else:
        date = date[6:] + '/' + date[:5]
    row['date'] = date
    row['text'] = text
    return row

In [194]:
clean_comps = exp.apply(sep_date,axis=1).reset_index().drop('index',axis=1)

In [196]:
grp = clean_comps.reset_index().groupby(['complaint_id','index']).sum()
#grp.to_csv('grp_test.csv',index_label=['url', 'complaint_id'])
grp

                                   complaint_type      status        date  \
complaint_id index
1299364647   279    Problems with Product/Service  Unanswered  2020/09/07
1299366377   270         Advertising/Sales Issues  Unanswered  2020/09/30
1299367493   535        Billing/Collection Issues  Unanswered  2022/04/11
1299367494   536    Problems with Product/Service  Unanswered  2020/07/15
1299367548   418    Problems with Product/Service  Unanswered  2022/05/03
...                                           ...         ...         ...
1593791409   634    Problems with Product/Service    Resolved  2023/05/30
             635    Problems with Product/Service    Resolved  2023/06/02
             636    Problems with Product/Service    Resolved  2023/06/02
1593791410   631    Problems with Product/Service    Answered  2023/06/05
             632    Problems with Product/Service    Answered  2023/06/14

                          description  \
complaint_id index
1299364647   279    Initial Complaint
1299366377   270    Initial Complaint
1299367493   535    Initial Complaint
1299367494   536    Initial Complaint
1299367548   418    Initial Complaint
...                               ...
1593791409   634    Customer response
             635    Business response
             636    Customer response
1593791410   631    Initial Complaint
             632    Business response

                                                                 text  \
complaint_id index
1299364647   279    I kept constantly complaining to my lanlord to...
1299366377   270    I gave 30 days notice paid an extra month at m...
1299367493   535    I put in a req to have my air conditioner main...
1299367494   536    Mice Office Management (Tara) Repairs I have b...
1299367548   418    April 21, ************************************...
...                                                               ...
1593791409   634           The community name is **** ******* *****\n
             635    We have investigated the complaint of the miss...
             636    Better Business Bureau:\n\nI have reviewed the...
1593791410   631    I noticed This issue on May 21st around 6pm du...
             632    On behalf of Bell Partners Inc. and the ******...

                                                                  url
complaint_id index
1299364647   279    https://www.bbb.org/us/tn/memphis/profile/apar...
1299366377   270    https://www.bbb.org/us/tn/memphis/profile/apar...
1299367493   535    https://www.bbb.org/us/tn/memphis/profile/apar...
1299367494   536    https://www.bbb.org/us/tn/memphis/profile/apar...
1299367548   418    https://www.bbb.org/us/tn/memphis/profile/apar...
...                                                               ...
1593791409   634    https://www.bbb.org/us/nc/greensboro/profile/p...
             635    https://www.bbb.org/us/nc/greensboro/profile/p...
             636    https://www.bbb.org/us/nc/greensboro/profile/p...
1593791410   631    https://www.bbb.org/us/nc/greensboro/profile/p...
             632    https://www.bbb.org/us/nc/greensboro/profile/p...

[1303 rows x 6 columns]

In [197]:
urls = [
    'https://www.bbb.org/us/tn/memphis/profile/apartments/the-residences-at-lakeview-0543-44158002',
    'https://www.bbb.org/us/tn/memphis/profile/apartments/mill-creek-apartments-0543-44074598',
    'https://www.bbb.org/us/tn/germantown/profile/property-management/maa-0543-31000112',
    'https://www.bbb.org/us/tn/memphis/profile/apartments/the-trails-at-mt-moriah-0543-44120390',
    'https://www.bbb.org/us/tn/memphis/profile/apartments/winchester-grove-apartments-0543-44141723'
]

In [204]:
def comp_url(df):
    return df['url'] + '/complaints#' + str(df['complaint_id'])

In [210]:
def get_df(u):
    df_url = clean_comps[clean_comps['url'] == u]
    df_url['url'] = df_url.apply(comp_url,axis=1)
    df_url = df_url.reset_index().groupby(['complaint_id','index']).sum()
    return u.split('-0543')[0].split('/')[-1], df_url

In [ ]:
by_url = [*map(get_df, urls)]

In [ ]:
df_other = clean_comps[~clean_comps.url.isin(urls)]
df_other['url'] = df_other.apply(comp_url,axis=1)
df_other = df_other.reset_index().groupby(['complaint_id','index']).sum()
by_url.append(('other', df_other))

In [213]:
with pd.ExcelWriter('output.xlsx') as writer:
    for n in by_url:
        n[1].to_excel(writer, sheet_name=n[0])